### ISSUE TITLE
Icons not displaying

### ISSUE THREAD

**Issue by amilajack** [henrikdahl/hyper-tabs-enhanced#2]
Icons are not displaying in the latest version of hyper. Any idea of what's causing this?

**Comment by henrikruscon** [comment]
@amilajack what does your hyper tab titles format look like?

**Comment by amilajack** [comment]
<img width="632" alt="screen shot 2017-01-12 at 12 03 57 pm" src="https://cloud.githubusercontent.com/assets/6374832/21906216/42863d92-d8bf-11e6-8fe0-1289e02b43fe.png">

**Comment by henrikruscon** [comment]
@amilajack 

I see, you have old style titles. Common one is `username: node` now.

I just pushed a new version to support old titles as well. Let me know if it works for you ✌️

**Comment by amilajack** [comment]
How can i make sure i install the latest version? This still wasnt fixed. I think i'm installing the old version

**Comment by henrikruscon** [comment]
Close hyper, comment out `hyper-tabs-enhanced` in your `hyper.js` and start Hyper, then close Hyper, comment it back in and start Hyper. Now you should have the latest version.

**Comment by amilajack** [comment]
hyper-statusline or hyper-tabs-enhanced?

**Comment by henrikruscon** [comment]
Haha sorry, working between both plugins getting me confused. It's `hyper-tabs-enhanced`

**Comment by amilajack** [comment]
I found out that works but only when disabling the `hyper-chesterish` theme.

**Comment by henrikruscon** [comment]
What plugins do you run?

`hyper-chesterish` doesn't do anything that affects tab icons, it's odd that it has any relation

**Comment by amilajack** [comment]
Here's what works for me:

<img width="463" alt="screen shot 2017-01-12 at 12 51 16 pm" src="https://cloud.githubusercontent.com/assets/6374832/21907778/d46e54a0-d8c5-11e6-8a5c-d75ad2c8c854.png">

**Comment by henrikruscon** [comment]
What happens when you enable `hyper-chesterish` then? Screen?

**Comment by henrikruscon** [comment]
Is this still an issue? @amilajack

**Comment by amilajack** [comment]
Nope. Thanks for fixing!
